packages:
  - "packages/*"
onlyBuiltDependencies:
  - esbuild
  - "@tarojs/binding"
  - "@tarojs/cli"
  - "@swc/core"
  - "@parcel/watcher"
  - core-js
  - core-js-pure
allowBuilds:
  esbuild: true
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
